### ISSUE TITLE
Script taking the official variables tables into account 

### ISSUE THREAD

**Issue by doblerone** [HCLIMcom/HCLIM2CMOR#22]
Creating the CORDEX6_CMOR_HCLIM_variables_table.csv is currently done manually (adaptation to CORDEX-CMIP5 & CCLM tables).

It would be good to ingest the official tables directly or have a script that converts them.

**Comment by ljoakim** [comment]
Adding @gnikulin 

I've started looking into this a bit, and probably the settings could be built from the official tables (from the cordex-cmip6-cmor-tables github) on the fly in `settings.py`, where currently the csv is read. A few questions just to make sure I'm on the right track:

1. The 'Level' column of the csv currently has one of two types, 'ModelLevel' or 'PressureLevel' (a third option, 'ZLevel' doesn't seem to be used). These values determine which coordinate, `plev` or `height`, is added to the variable [here](https://github.com/HCLIMcom/HCLIM2CMOR/blob/1134dc07d049422f4923515a635471bda7d5ab0c/src/CMORlight/tools.py#L1629). Am I correct in thinking the type should be determined by looking at the "out_name" of the coords used by a variable?

2. For the csv aggregation columns ("ag"), which determines the time bounds [here](https://github.com/HCLIMcom/HCLIM2CMOR/blob/1134dc07d049422f4923515a635471bda7d5ab0c/src/CMORlight/tools.py#L142C14-L142C15), I assume the variable's "cell_method" determines whether it should be "i" (instantaneous) or "a" (aggregated)? (It seems even the last word is enough: "point" or "mean")

3. The three last columns, 'direction of positive fluxes', 'realm' and 'cell-method:area' I don't find used anywhere. Are they needed, and if so, what values should go there? (There are probably more columns that are not used.)

4. Finally a question regarding a specific variable: cape. In the official tables the variable name and its "out_name" is "cape", but in the current csv table, the output name is "CAPE" (uppercase), which is what is used in the data request (https://cordex.org/experiment-guidelines/cordex-cmip6/data-request-cordex-cmip6-rcms). Is there an error in the cmor-tables, or am I missing something?

**Comment by ljoakim** [comment]
I'm going on a one-week vacation next week, and I'll get back to this after. We had some discussion, and the general idea is to keep a local csv variable table with *some*, more permanent and well known, information that is not explicitly available in the github tables, and to download the github tables and merge information with the local table to produce a csv table properly formatted for use by HCLIM2CMOR. The generated table can replace the existing one, and be committed to this repo whenever updated.

I'll implement this in a separate utility script which can be run (manually) when updates to the github tables have been made.

If this for some reason seems infeasible in any part, or if there is something I seem to be missing, let me know.
