### ISSUE TITLE
Fix format of creation_date

### ISSUE THREAD

**Issue by ljoakim** [HCLIMcom/HCLIM2CMOR#34]
The format of output `creation_date` is currently `YYYY-MM-DD HH:MM:SS`, should be `YYYY-MM-DDTHH:MM:SSZ`.

**Comment by doblerone** [comment]
In the CORDEX-CMIP6 archiving specifications 
https://doi.org/10.5281/zenodo.10961068
the table says the format should be YYYY-MM-DDTHH:MM:SSZ, but the example is
;creation_date="2023-11-19 18:01:15";
@gnikulin Should we fix that in the archiving specifications (i.e. that the example is correct)?
