### ISSUE TITLE
Handle prhmax in cmorization

### ISSUE THREAD

**Issue by ljoakim** [HCLIMcom/HCLIM2CMOR#37]
`prhmax` has a particular type of `cell_method` which is currently not handled by cmorization in `tools.py` (in code from [here](https://github.com/HCLIMcom/HCLIM2CMOR/blob/b41f316cb87cb43080f00bc5e5c1ee20bf57e42d/src/CMORlight/tools.py#L1422) and downwards). This needs to be fixed, see discussion here: [https://github.com/WCRP-CORDEX/discuss/issues/7](https://github.com/WCRP-CORDEX/discuss/issues/7).

**Comment by doblerone** [comment]
What is the current behaviour for `prhmax` @ljoakim ?
Does it correctly read the daily `cm_type` from the table, i.e. `area: mean time: mean within hours time: maximum over hours`?
https://github.com/HCLIMcom/HCLIM2CMOR/blob/b41f316cb87cb43080f00bc5e5c1ee20bf57e42d/src/CMORlight/tools.py#L1344-L1346
(Debug info here)
https://github.com/HCLIMcom/HCLIM2CMOR/blob/72c7a3ea2cf467eef247a598b9339f13c52121d8/src/CMORlight/tools.py#L1363-L1366

and write?
https://github.com/HCLIMcom/HCLIM2CMOR/blob/72c7a3ea2cf467eef247a598b9339f13c52121d8/src/CMORlight/tools.py#L1699

And does the prhmax cmorization enter this if statement here?
(and what is `cm` there?)
https://github.com/HCLIMcom/HCLIM2CMOR/blob/72c7a3ea2cf467eef247a598b9339f13c52121d8/src/CMORlight/tools.py#L1439-L1441
This will not work I guess.

**Comment by doblerone** [comment]
> It has been decided to delete this variable form the monthly frequency table, only left in the day table.

I have removed the monthly `prhmax` entry from the table 
https://github.com/HCLIMcom/HCLIM2CMOR/blob/master/src/CMORlight/Config/CORDEX6_CMOR_HCLIM_variables_table.csv

**Comment by doblerone** [comment]
Thanks!
OK, so (as expected) it goes into the elif at line 1440 above, with cm="mean within hours time: maximum over hours", and causes cdo to abort.
We don't need to run an additional cdo command here because prhmax is already calculated as daymax in mergemon.sh.
So we need to find a clever way to skip this. A quick and dirty solution would be easy to implement (skip in case var=prhmax) but maybe we can come up with a more general one that handles `cm_type=area: mean time: mean within hours time: maximum over hours`

I'll have a look at it tomorrow.

**Comment by doblerone** [comment]
Alternatively, we could make a copy of hourly `pr` in mergemon.sh for the variable `prhmax` and then make a daymax in line 1440 to get the daily `prhmax` (analog tasmax etc.). I.e. we try to extract the "max" from the string `time: mean within hours time: maximum over hours`

**Comment by gnikulin** [comment]
and our final solution ? :-)

**Comment by doblerone** [comment]
I didn't have time to implement and test it. It's a nasty variable. I'd think the easiest and most flexible solution is to add another if statement here https://github.com/HCLIMcom/HCLIM2CMOR/blob/72c7a3ea2cf467eef247a598b9339f13c52121d8/src/CMORlight/tools.py#L1439-L1441
e.g.
`if res == 'day' and 'maximum over hours' in cm_type: `
`    cmd = "cdo -L -f %s -s daymax -seltimestep,%s %s %s %s" %(config.get_config_value('settings','cdo_nctype'),tsteps,cmd_mul,in_file,ftmp_name)`
`else`

This should work both if 
1) `prhmax` is prodced as `daymax(pr_1h)` in `mergemon.sh` as it is done now. Then the `daymax` is simply done twice.
2) `prhmax=daymax(pr_ah)` is done in `master_cmor.sh`. Then the `prhmax` entry in the table https://github.com/HCLIMcom/HCLIM2CMOR/blob/master/src/CMORlight/Config/CORDEX6_CMOR_HCLIM_variables_table.csv needs to start with `pr;pr;prhmax` and hurly `pr` needs to be available in `input_CMORlight`

@ljoakim can you implement and test this? If you don't have the time, I can give it a try.

**Comment by ljoakim** [comment]
I'll look into it tomorrow and test it.
