### ISSUE TITLE
6-houtly output: StartTime and EndTime in the file name without minutes ? 

### ISSUE THREAD

**Issue by gnikulin** [HCLIMcom/HCLIM2CMOR#42]
I saw examples of the 6-hr output posprocessed for the ERA5-driven simulation, e.g. 
`mrros_EUR-12_ERA5_evaluation_r1i1p1f1_HCLIMcom-SMHI-HCLIM43-ALADIN_v1-r1_6hr_1985010103-1985123121.nc`.

Both StartTime and EndTime have format "YYYYMMDDhh" as in CORDEX-CMIP5 but in CORDEX-CMIP6 the format for subdaily output must include minutes as well "YYYYMMDDhhmm". Perhaps, it's simply an "artefact" from CORDEX-CMIP5 which easy to fix.

**Comment by doblerone** [comment]
I was not aware of that change from CORDEX-CMIP5 to CORDEX-CMIP6. Well hidden in the Archiving Specifications :-)
Thanks for pointing that out!
I just saw that Joakim already has a pull request. I will check.

**Comment by ljoakim** [comment]
Closed with PR #43
