### ISSUE TITLE
evspsbl:positive = "up" ??

### ISSUE THREAD

**Issue by gnikulin** [HCLIMcom/HCLIM2CMOR#45]
I see that evspsbl has the positive attribute = "up" `evspsbl:positive = "up"` while this attribute is not required in CORDEX-CMIP6 or CMIP6, simply empty `"positive": ""` in the CORDEX-CMIP6 CMOR tables. It seems that the positive attribute for evspsbl is hard coded somewhere ?

**Comment by doblerone** [comment]
This is inherrited from the original data, e.g.
/nobackup/rossby27/proj/rossby/joint_exp/cordex/202201/run/archive/1989/03/01/00/evspsbl_fp_EUR11_EUR11_ALADIN43_v1_ERA5_r1i1p1f1_eval_1hr_198903010000-198904010000.nc
--> 	evspsbl:positive = "up" ;

The tool does not seem to remove this at the moment.

**Comment by ljoakim** [comment]
Is it a special case for this variable, or are there others that should have the attribute `positive = "up"` removed? Maybe it can be fixed as a special case in the solution to #46.

**Comment by doblerone** [comment]
The direction of positive fluxes is defined in 
https://github.com/HCLIMcom/HCLIM2CMOR/blob/master/src/CMORlight/Config/CORDEX6_CMOR_HCLIM_variables_table.csv
(actually empty for evspsbl).
If we can remove the attribute :positive = "up" from the original files and set them according to the table afterwards this should work, right?

**Comment by ljoakim** [comment]
If it's easy to remove them from the original files, that should fix it.

I'm searching the source code, and I actually don't find anywhere where the direction of positive fluxes is used to set the `positive` attribute. Maybe I'm just missing it. The attribute is set in a few places, but the value is hard coded.

**Comment by ljoakim** [comment]
For clarification, how should we deal with this?
1. Should the attribute be removed from the original files, i.e. the output from HCLIM if I understand correctly, or,
2. should we add a special case for this variable in the code? If so, are there more variables which have this attribute, but shouldn't? Or
3. should we enforce what is in the table, and maybe remove the attribute altogether if its entry in the table is empty? (The column header is "direction of positive fluxes", does that make sense for all variables that should have the attribute "positive"? Are there variables which will have the attribute "positive" in the original data, and an empty entry in the table, but should preserve the attribute value from the original?)

**Comment by doblerone** [comment]
Hi

I think 3):
We should enforce what is in the table and also remove the attribute when
the column is empty.
The table gives the user much flexibility, e.g. also for other models or to
change the positive direction from "down" in the original model output to
"up" in the CMORises files for instance.

Variables which will have the attribute "positive" in the original data,
and an empty entry in the table, should NOT preserve the attribute value
from the original.




Joakim Löw ***@***.***> schrieb am Fr., 27. Sept. 2024, 09:36:

**Comment by gnikulin** [comment]
Can we delete all attributes created by HCLIM and then create only necessary attributes defined in the CMOR tables ?

**Comment by ljoakim** [comment]
It should be possible to not transfer any attributes from the original target variable, and let the cmor step create necessary variables. I'll run a test to get a feeling for what changes are needed in the code. If we take this approach, I believe that nullifies #46/#47.

Are there never any attributes that should be transferred (for the target variable)?
