### ISSUE TITLE
internal HCLIM variable attributes 

### ISSUE THREAD

**Issue by gnikulin** [HCLIMcom/HCLIM2CMOR#46]
There are several internal HCLIM variable attributes left after postprocessing (FA_name, par, lvt, lev, tri and uvRelativeToGrid for wind) e.g.

```
float evspsbl(time, y, x) ;
		evspsbl:_FillValue = 1.e+20f ;
		evspsbl:standard_name = "water_evapotranspiration_flux" ;
		evspsbl:long_name = "Evaporation Including Sublimation and Transpiration" ;
		evspsbl:units = "kg m-2 s-1" ;
		evspsbl:positive = "up" ;
		evspsbl:FA_name = "SURFFLU.MTOTA.NE" ;
		evspsbl:par = 211 ;
		evspsbl:lvt = "heightAboveGround" ;
		evspsbl:lev = 0 ;
		evspsbl:tri = 3 ;
		evspsbl:grid_mapping = "crs" ;
		evspsbl:cell_methods = "area: time: mean" ;
		evspsbl:coordinates = "lat lon" ;
		evspsbl:missing_value = 1.e+20f ;
```
or

```
float uas(time, y, x) ;
		uas:_FillValue = 1.e+20f ;
		uas:standard_name = "eastward_wind" ;
		uas:units = "m s-1" ;
		uas:FA_name = "CLSVENT.ZONAL" ;
		uas:par = 33 ;
		uas:lvt = "heightAboveGround" ;
		uas:lev = 10 ;
		uas:tri = 0 ;
		uas:uvRelativeToGrid = 0 ;
		uas:long_name = "Eastward Near-Surface Wind" ;
		uas:cell_methods = "area: time: mean" ;
		uas:grid_mapping = "crs" ;
		uas:coordinates = "height lat lon" ;
		uas:missing_value = 1.e+20f ;
```

These attributes are not requested and it's fine to keep them.  I'm only not sure if these attributes are useful and going to be used ? Perhaps, we need to clean them up from the postprocessed files ?

**Comment by doblerone** [comment]
I don't have a strong opinion on that.
The FA_name and par might be useful to some users (it was to me at some point) and I like the lvt and lev information in the ncdump without the need to go to cdo showlevel.
However, removing them makes the files look more tidy of course.

**Comment by gnikulin** [comment]
So who makes decision :-) considering that 99.9% of users have no idea what these attributes mean ?

**Comment by doblerone** [comment]
And probably also adjust the tool to remove them. If I remember correctly there is a setting for that somewhere.
@ljoakim do you remember if variable attributes that should be removed can be set (and where)?

**Comment by ljoakim** [comment]
I was looking for something like that, but I don't have any recollection of such a setting (for target variable attributes). But it should be straightforward to add if needed. Which attributes should be removed?

**Comment by doblerone** [comment]
I mixed that up with "dimensions that should no be copied to output files"
The attributes FA_name, par, lvt, lev, tri and uvRelativeToGrid (for wind) should be removed.

**Comment by ljoakim** [comment]
And they should always be removed if they are among the target variable attributes, regardless of variable?

**Comment by doblerone** [comment]
> And they should always be removed if they are among the target variable attributes, regardless of variable?

Yes

**Comment by ljoakim** [comment]
> And probably also adjust the tool to remove them. If I remember correctly there is a setting for that somewhere.
> @ljoakim do you remember if variable attributes that should be removed can be set (and where)?

There is a setting in the control_cmor ini file, `attrlist_reject`, containing a few of the attributes to be removed. It just never seems to be used. I'll add the necessary code and make a PR.
