### ISSUE TITLE
mrfsos and mrsos produces RuntimeError

### ISSUE THREAD

**Issue by ljoakim** [HCLIMcom/HCLIM2CMOR#50]
`mrsos`and `mrfsos` currently produces `RuntimeError: NetCDF: String match to name in use` at this line:

https://github.com/HCLIMcom/HCLIM2CMOR/blob/d831d0d619d2495d1d2cb32211ce29d0088a5fd1/src/CMORlight/tools.py#L1759

**Comment by gnikulin** [comment]
It looks like `bnds` already exists, should be related to `time_bnds`, although both variables are instantaneous output. Does the error appear during postprocessing of  1-hr data ?

**Comment by ljoakim** [comment]
> Does the error appear during postprocessing of 1-hr data ?

A bit unclear from the logs, but it seems it appears at day resolution. My guess is `bnds` is created at 1hr, then raises the error for day. Probably a check is needed, which is done in a later if-block for 'mrsol','mrsfl','tsl' some lines below:

https://github.com/HCLIMcom/HCLIM2CMOR/blob/d831d0d619d2495d1d2cb32211ce29d0088a5fd1/src/CMORlight/tools.py#L1781-L1782

**Comment by ljoakim** [comment]
Adding the if statement seems to have fixed it. I've successfully run `mrsos`, currently running `mrfsos`. I'll make a PR as soon as it's done.
