### ISSUE TITLE
mrro and clwvi not produced

### ISSUE THREAD

**Issue by ljoakim** [HCLIMcom/HCLIM2CMOR#51]
`mrro` and `clwvi` are not produced. They both rely on other variables to be calculated:
- `mrro = mrros + mrrod`
- `clwvi = clqvi + clivi`

`mrrod` and `clqvi` are not available in any tables, although they exists in the "original" HCLIM output. With no entry in the table, they will not be processed. Looking in the logs however, it seems the tool expects them to be postprocessed before `mrro`and `clwvi` can be produced.

**Comment by gnikulin** [comment]
as I see both `mrro` and  `clwvi` should be produced in 

https://github.com/HCLIMcom/HCLIM2CMOR/blob/23178b08a1eee90a9ca3bc0bdb7df571bb95476a/src/hclim_post/mergemon.sh#L456-L462

@doblerone  ?

**Comment by doblerone** [comment]
Yes, that is where additional fields for CORDEX not directly available in the HCLIM output are generated. It uses simple cdo commands. The first 2 arguments to the create_add_vars call are the input variables, third is the output variable, then the cdo command and last the cf_standard_name of the output variable.

clwvi, mrro (and prhmax) are defined as additional variables in 
https://github.com/HCLIMcom/HCLIM2CMOR/blob/23178b08a1eee90a9ca3bc0bdb7df571bb95476a/src/hclim_post/mergemon.sh#L31-L32
